### ISSUE TITLE
Connection issues, followed by lock-up

### ISSUE THREAD

**Issue by cohaolain** [cohaolain/ContainerisedIrishRailDataCapture#3]
# Issue
Application is encountering connection issues (might be rate-limiting, etc.) and is later locking up complete, but **not** crashing.

Log is included here: [ir-logger.log](https://github.com/cohaolain/ContainerisedIrishRailDataCapture/files/4021925/ir-logger.log)

So far I've been unable to find out specifically why the application is locking up after several retry attempts. Unfortunately I don't have info **yet** as to the timescale of the issues in the above log, if they were linked or how soon after these errors the application locked up after these errors occurred. 

For now, I'm going to restart the logger, it's been down all Christmas unfortunately... I haven't figured out what caused the lock-up yet but if I don't realise soon, perhaps the improvements in #1 will help accelerate debugging this issue.

# Proposed Fix
None yet.

**Comment by cohaolain** [comment]
Application now terminated and restarted:
```
^CTraceback (most recent call last):
  File "./logger.py", line 53, in <module>
    raw_data = getData()
  File "./logger.py", line 19, in getData
    return requests.get(url).content
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```
